apiVersion: v1
kind: Service
metadata:
  name: spring-argocd-app
spec:
  selector:
    app: spring-argocd-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-argocd-app
spec:
  selector:
    matchLabels:
      app: spring-argocd-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-argocd-app
    spec:
      containers:
        - name: spring-argocd-app
          image: ihl79dev/spring-argocd-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-argocd-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "spring-app.test.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-argocd-app
                port:
                  number: 8080
